CREATE DATABASE Woop

USE Woop

CREATE TABLE Users (
	UserID INT,
	FirstName VARCHAR(255),
	LastName VARCHAR(255),
	School VARCHAR(255),
	UserAddress VARCHAR(255),
	Email VARCHAR(255),
	PhoneNumber VARCHAR(20),
	UserLocation VARCHAR(255),
	DateOfBirth date,
	Gender char(1)
	CONSTRAINT UsersPK PRIMARY KEY(UserID),
	CONSTRAINT EmailCheck CHECK(Email LIKE '%@%'),
	CONSTRAINT GenderCheck CHECK(Gender LIKE 'M' OR Gender LIKE 'F'),
)

CREATE TABLE Friend (
	FriendID INT,
	UserID INT,
	CONSTRAINT FriendPK PRIMARY KEY(FriendID),
	CONSTRAINT FriendFK1 FOREIGN KEY(UserID) REFERENCES Users(UserID) ON UPDATE CASCADE ON DELETE CASCADE,
)


CREATE TABLE Pages (
	PageID INT,
	PageName VARCHAR(255),
	PageContent VARCHAR(255),
	CONSTRAINT PagePK PRIMARY KEY(PageID),
)

CREATE TABLE PageLikes (
	PageLikesID INT,
	PageID INT,
	UserID INT,
	CONSTRAINT PageLikesPK PRIMARY KEY(PageLikesID),
	CONSTRAINT PageLikesFK1 FOREIGN KEY(PageID) REFERENCES Pages(PageID) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT PageLikesFK2 FOREIGN KEY(UserID) REFERENCES Users(UserID) ON UPDATE CASCADE ON DELETE CASCADE,
)

CREATE TABLE Posts (
	PostsID INT,
	UserID INT,
	PostContent VARCHAR(255),
	PostDate date,
	CONSTRAINT PostsPK PRIMARY KEY(PostsID),
	CONSTRAINT PostsFK1 FOREIGN KEY(UserID) REFERENCES Users(UserID) ON UPDATE CASCADE ON DELETE CASCADE,
)

CREATE TABLE PostLikes (
	PostLikeID INT,
	PostID INT,
	UserID INT,
	CONSTRAINT PostLikePK PRIMARY KEY(PostLikeID),
	CONSTRAINT PostLikeFK1 FOREIGN KEY(PostID) REFERENCES Posts(PostsID) ON UPDATE CASCADE ON DELETE SET NULL,
	CONSTRAINT PostLikeFK2 FOREIGN KEY(UserID) REFERENCES Users(UserID) ON UPDATE NO ACTION ON DELETE NO ACTION,
)

CREATE TABLE Photos (
	PhotoID INT,
	PostID INT,
	ImageContent VARCHAR(255),
	CONSTRAINT PhotosPK PRIMARY KEY(PhotoID),
	CONSTRAINT PhotosFK1 FOREIGN KEY(PostID) REFERENCES Posts(PostsID) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT ImageCheck CHECK(ImageContent LIKE 'http://*.jpg' or ImageContent LIKE 'https://*.jpg' or ImageContent LIKE 'http://.png' or ImageContent LIKE 'https://.png' or ImageContent LIKE 'http://.jpeg' or ImageContent LIKE 'https://.jpeg')
)

CREATE TABLE Shares (
	ShareID INT,
	PostID INT,
	UserID INT,
	CONSTRAINT SharePK PRIMARY KEY(ShareID),
	CONSTRAINT ShareFK1 FOREIGN KEY(PostID) REFERENCES Posts(PostsID) ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT ShareFK2 FOREIGN KEY(UserID) REFERENCES Users(UserID) ON UPDATE NO ACTION ON DELETE NO ACTION,
)

CREATE TABLE Comments (
	CommentID INT,
	PostID INT,
	UserID INT,
	CommentContent VARCHAR(255),
	CommentDate date,
	CONSTRAINT CommentPK PRIMARY KEY(CommentID),
	CONSTRAINT CommentFK1 FOREIGN KEY(PostID) REFERENCES Posts(PostsID) ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT CommentFK2 FOREIGN KEY(UserID) REFERENCES Users(UserID) ON UPDATE NO ACTION ON DELETE NO ACTION,
)

CREATE TABLE CommentLike (
	CommentLikeID INT,
	CommentID INT,
	UserID INT,
	CONSTRAINT CommentLikePK PRIMARY KEY(CommentLikeID),
	CONSTRAINT CommentLikeFK1 FOREIGN KEY(CommentID) REFERENCES Comments(CommentID) ON UPDATE NO ACTION ON DELETE CASCADE,
	CONSTRAINT CommentLikeFK2 FOREIGN KEY(UserID) REFERENCES Users(UserID) ON UPDATE NO ACTION ON DELETE CASCADE,
)